version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 967914931466.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nodeapp:version2 .
  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag nodeapp:version2 967914931466.dkr.ecr.us-east-1.amazonaws.com/nodeapp:version2
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 967914931466.dkr.ecr.us-east-1.amazonaws.com/nodeapp:version2
